[package]
name = "nox"
version = "1.2.1"
edition = "2024"
description = "The Nox Build & Automation System"
license = "Unlicense"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
noml = { path = "./noml" }
askalono = "0.5"
license = "3.8"
