use crate::core::error::{Error, Result};
use std::fs;
use std::path::{Path, PathBuf};

pub struct BuildState {
    pub root: PathBuf,
    pub build_dir: PathBuf,
    pub configuration: String,
    pub compiler: String,
    pub linker: String,
    pub archiver: String,
    pub compile_flags: Vec<String>,
}

impl BuildState {
    pub fn path(build_dir: &Path) -> PathBuf {
        build_dir.join("nox.state")
    }

    pub fn save(&self) -> Result<()> {
        fs::create_dir_all(&self.build_dir)?;
        let content = format!(
            "// This file is generated by nox.\n// It is not intended to be manually edited.\nroot={}\nconfiguration={}\ncompiler={}\nlinker={}\narchiver={}\n{}",
            quote_state_value(&self.root.display().to_string()),
            quote_state_value(&self.configuration),
            quote_state_value(&self.compiler),
            quote_state_value(&self.linker),
            quote_state_value(&self.archiver),
            self.compile_flags
                .iter()
                .map(|flag| format!("compile_flag={}\n", quote_state_value(flag)))
                .collect::<String>()
        );
        fs::write(Self::path(&self.build_dir), content)?;
        Ok(())
    }

    pub fn load(build_dir: &Path) -> Result<Self> {
        let text = fs::read_to_string(Self::path(build_dir)).map_err(|_| {
            Error::Config(format!(
                "'{}' is not configured; run nox setup {}",
                build_dir.display(),
                build_dir.display()
            ))
        })?;
        let mut values = std::collections::HashMap::new();
        let mut compile_flags = Vec::new();
        for line in text.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("//") {
                continue;
            }
            let (key, value) = trimmed
                .split_once('=')
                .ok_or_else(|| Error::Config("invalid build state".to_string()))?;
            let value = unquote_state_value(value);
            if key == "compile_flag" {
                compile_flags.push(value);
            } else {
                values.insert(key, value);
            }
        }
        Ok(Self {
            root: PathBuf::from(
                values
                    .remove("root")
                    .ok_or_else(|| Error::Config("build state has no root".to_string()))?,
            ),
            build_dir: build_dir.to_path_buf(),
            configuration: values
                .remove("configuration")
                .unwrap_or_else(|| "debug".to_string()),
            compiler: values
                .remove("compiler")
                .unwrap_or_else(|| "cc".to_string()),
            linker: values.remove("linker").unwrap_or_else(|| "cc".to_string()),
            archiver: values
                .remove("archiver")
                .unwrap_or_else(|| "ar".to_string()),
            compile_flags,
        })
    }
}

fn quote_state_value(value: &str) -> String {
    if value.chars().any(char::is_whitespace) || value.contains('"') {
        format!("\"{}\"", value.replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

fn unquote_state_value(value: &str) -> String {
    let trimmed = value.trim();
    trimmed
        .strip_prefix('"')
        .and_then(|value| value.strip_suffix('"'))
        .map(|value| value.replace("\\\"", "\""))
        .unwrap_or_else(|| trimmed.to_string())
}
